use std::sync::Arc;

use base64::Engine;
use chrono::Utc;
use rig_core::{
    OneOrMany,
    message::{ImageMediaType, Message, MimeType, UserContent},
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    agents::agent::model::{VizierModel, VizierModelTrait},
    agents::tools::{ToolContext, VizierTool},
    error::VizierError,
    file_manager::FileManager,
    schema::{VizierResponse, VizierResponseContent},
    storage::{VizierStorage, session_file::SessionFileStorage},
};

const DEFAULT_VISION_PROMPT: &str = "Describe this image in detail.";

#[derive(Debug, Deserialize, Serialize, JsonSchema)]
pub struct ReadImageFileArgs {
    #[schemars(description = "filename of the session image file to read")]
    pub filename: String,
    #[schemars(
        description = "Optional additional prompt for the vision model. Honored only when the \
        read_image tool is configured with a provider+model (vision mode). Ignored in the default \
        attachment-injection flow."
    )]
    pub prompt: Option<String>,
}

pub struct ReadImageFile {
    pub storage: Arc<VizierStorage>,
    pub file_manager: FileManager,
    /// Pre-built vision-capable model. When `Some`, the tool runs a single-turn
    /// completion and returns its text. When `None`, the tool returns the image
    /// as an attachment for the main agent to see directly.
    pub vision: Option<VizierModel>,
}

#[async_trait::async_trait]
impl VizierTool for ReadImageFile {
    type Input = ReadImageFileArgs;
    type Output = VizierResponse;

    fn name() -> String {
        "read_image_file".to_string()
    }

    fn description(&self) -> String {
        match &self.vision {
            Some(_) => "Read an image file from the current session and return a text \
                description generated by a configured vision model. The file must have an \
                image/* MIME type. Use read_document_file for textual documents, PDFs, and \
                spreadsheets. You may pass an optional `prompt` to steer the description."
                .to_string(),
            None => "Read an image file from the current session and inject it into the \
                conversation context as a vision attachment. The file must have an image/* \
                MIME type; use read_document_file for textual documents, PDFs, and \
                spreadsheets."
                .to_string(),
        }
    }

    async fn call(
        &self,
        args: Self::Input,
        ctx: &ToolContext,
    ) -> Result<Self::Output, VizierError> {
        let file = self
            .storage
            .get_session_file(&ctx.session, &args.filename)
            .await
            .map_err(|e| VizierError(e.to_string()))?
            .ok_or_else(|| VizierError(format!("File not found: {}", args.filename)))?;

        if !file.mime_type.starts_with("image/") {
            return Err(VizierError(format!(
                "read_image_file requires an image/* MIME type, got '{}'. Use read_document_file for this file.",
                file.mime_type
            )));
        }

        let (_, content) = self
            .file_manager
            .get(&file.file_id)
            .await
            .map_err(|e| VizierError(e.to_string()))?;

        let b64 = base64::engine::general_purpose::STANDARD.encode(&content);

        if let Some(vision) = &self.vision {
            let media_type =
                ImageMediaType::from_mime_type(&file.mime_type).unwrap_or(ImageMediaType::PNG);
            let prompt = args
                .prompt
                .as_deref()
                .map(str::trim)
                .filter(|p| !p.is_empty())
                .unwrap_or(DEFAULT_VISION_PROMPT)
                .to_string();

            let message = Message::User {
                content: OneOrMany::many(vec![
                    UserContent::Text(prompt.into()),
                    UserContent::image_base64(b64, Some(media_type), None),
                ])
                .unwrap(),
            };

            let (_, choices, _) = vision
                .completion(message, vec![], vec![])
                .await
                .map_err(|e| VizierError(e.to_string()))?;

            let text = choices
                .iter()
                .filter_map(|c| match c {
                    rig_core::message::AssistantContent::Text(t) => Some(t.text.clone()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("\n");
            return Ok(VizierResponse {
                timestamp: Utc::now(),
                content: VizierResponseContent::ToolResponse {
                    response: serde_json::Value::String(text),
                },
                attachments: vec![],
            });
        }

        Ok(VizierResponse {
            timestamp: Utc::now(),
            content: VizierResponseContent::ToolResponse {
                response: serde_json::Value::String(format!(
                    "Loaded {} into context.",
                    file.filename
                )),
            },
            attachments: vec![crate::schema::VizierAttachment {
                filename: file.filename,
                content: crate::schema::VizierAttachmentContent::Base64(b64),
            }],
        })
    }
}
