use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EmbeddingConfig {
    Local { model: LocalEmbeddingModelVariant },
    Openrouter { model: String },
    Ollama { model: String },
    Openai { model: String },
    Gemini { model: String },
}

pub const LOCAL_EMBEDDING_MODELS: &[(&str, &str)] = &[
    ("all_mini_lml6_v2", "lightweight"),
    ("all_mini_lml6_v2q", "lightweight"),
    ("all_mini_lml12_v2", "performance"),
    ("all_mini_lml12_v2q", "balanced"),
    ("bge_base_env15", "balanced"),
    ("bge_base_env15q", "balanced"),
    ("bge_large_env15", "performance"),
    ("bge_large_env15q", "balanced"),
    ("bge_small_env15", "lightweight"),
    ("bge_small_env15q", "lightweight"),
    ("nomic_embed_text_v1", "balanced"),
    ("nomic_embed_text_v15", "balanced"),
    ("nomic_embed_text_v15q", "balanced"),
    ("paraphrase_ml_mini_lml12_v2", "lightweight"),
    ("paraphrase_ml_mini_lml12_v2q", "lightweight"),
    ("paraphrase_ml_mpnet_base_v2", "balanced"),
    ("bge_small_zh_v15", "lightweight"),
    ("bge_large_zh_v15", "performance"),
    ("modernbert_embed_large", "performance"),
    ("multilingual_e5_small", "lightweight"),
    ("multilingual_e5_base", "balanced"),
    ("multilingual_e5_large", "performance"),
    ("mxbai_embed_large_v1", "performance"),
    ("mxbai_embed_large_v1q", "balanced"),
    ("gte_base_env15", "balanced"),
    ("gte_base_env15q", "balanced"),
    ("gte_large_env15", "performance"),
    ("gte_large_env15q", "balanced"),
    ("clip_vit_b32", "balanced"),
    ("jina_embeddings_v2_base_code", "balanced"),
];

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LocalEmbeddingModelVariant {
    AllMiniLml6V2,
    AllMiniLml6V2Q,
    AllMiniLml12V2,
    AllMiniLml12V2Q,
    BgeBaseEnv15,
    BgeBaseEnv15Q,
    BgeLargeEnv15,
    BgeLargeEnv15Q,
    BgeSmallEnv15,
    BgeSmallEnv15Q,
    NomicEmbedTextV1,
    NomicEmbedTextV15,
    NomicEmbedTextV15Q,
    ParaphraseMlMiniLML12V2,
    ParaphraseMlMiniLML12V2Q,
    ParaphraseMlMpnetBaseV2,
    BgeSmallZhv15,
    BgeLargeZhv15,
    ModernBertEmbedLarge,
    MultilingualE5Small,
    MultilingualE5Base,
    MultilingualE5Large,
    MxbaiEmbedLargeV1,
    MxbaiEmbedLargeV1Q,
    GteBaseEnv15,
    GteBaseEnv15Q,
    GteLargeEnv15,
    GteLargeEnv15Q,
    ClipVitB32,
    JinaEmbeddingsV2BaseCode,
}

impl LocalEmbeddingModelVariant {
    pub fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "all_mini_lml6_v2" => Self::AllMiniLml6V2,
            "all_mini_lml6_v2q" => Self::AllMiniLml6V2Q,
            "all_mini_lml12_v2" => Self::AllMiniLml12V2,
            "all_mini_lml12_v2q" => Self::AllMiniLml12V2Q,
            "bge_base_env15" => Self::BgeBaseEnv15,
            "bge_base_env15q" => Self::BgeBaseEnv15Q,
            "bge_large_env15" => Self::BgeLargeEnv15,
            "bge_large_env15q" => Self::BgeLargeEnv15Q,
            "bge_small_env15" => Self::BgeSmallEnv15,
            "bge_small_env15q" => Self::BgeSmallEnv15Q,
            "nomic_embed_text_v1" => Self::NomicEmbedTextV1,
            "nomic_embed_text_v15" => Self::NomicEmbedTextV15,
            "nomic_embed_text_v15q" => Self::NomicEmbedTextV15Q,
            "paraphrase_ml_mini_lml12_v2" => Self::ParaphraseMlMiniLML12V2,
            "paraphrase_ml_mini_lml12_v2q" => Self::ParaphraseMlMiniLML12V2Q,
            "paraphrase_ml_mpnet_base_v2" => Self::ParaphraseMlMpnetBaseV2,
            "bge_small_zh_v15" => Self::BgeSmallZhv15,
            "bge_large_zh_v15" => Self::BgeLargeZhv15,
            "modernbert_embed_large" => Self::ModernBertEmbedLarge,
            "multilingual_e5_small" => Self::MultilingualE5Small,
            "multilingual_e5_base" => Self::MultilingualE5Base,
            "multilingual_e5_large" => Self::MultilingualE5Large,
            "mxbai_embed_large_v1" => Self::MxbaiEmbedLargeV1,
            "mxbai_embed_large_v1q" => Self::MxbaiEmbedLargeV1Q,
            "gte_base_env15" => Self::GteBaseEnv15,
            "gte_base_env15q" => Self::GteBaseEnv15Q,
            "gte_large_env15" => Self::GteLargeEnv15,
            "gte_large_env15q" => Self::GteLargeEnv15Q,
            "clip_vit_b32" => Self::ClipVitB32,
            "jina_embeddings_v2_base_code" => Self::JinaEmbeddingsV2BaseCode,
            _ => return None,
        })
    }

    pub fn to_fastembed(&self) -> fastembed::EmbeddingModel {
        match self {
            Self::AllMiniLml6V2 => fastembed::EmbeddingModel::AllMiniLML6V2,
            Self::AllMiniLml6V2Q => fastembed::EmbeddingModel::AllMiniLML6V2Q,
            Self::AllMiniLml12V2 => fastembed::EmbeddingModel::AllMiniLML12V2,
            Self::AllMiniLml12V2Q => fastembed::EmbeddingModel::AllMiniLML12V2Q,
            Self::BgeBaseEnv15 => fastembed::EmbeddingModel::BGEBaseENV15,
            Self::BgeBaseEnv15Q => fastembed::EmbeddingModel::BGEBaseENV15Q,
            Self::BgeLargeEnv15 => fastembed::EmbeddingModel::BGELargeENV15,
            Self::BgeLargeEnv15Q => fastembed::EmbeddingModel::BGELargeENV15Q,
            Self::BgeSmallEnv15 => fastembed::EmbeddingModel::BGESmallENV15,
            Self::BgeSmallEnv15Q => fastembed::EmbeddingModel::BGESmallENV15Q,
            Self::NomicEmbedTextV1 => fastembed::EmbeddingModel::NomicEmbedTextV1,
            Self::NomicEmbedTextV15 => fastembed::EmbeddingModel::NomicEmbedTextV15,
            Self::NomicEmbedTextV15Q => fastembed::EmbeddingModel::NomicEmbedTextV15Q,
            Self::ParaphraseMlMiniLML12V2 => fastembed::EmbeddingModel::ParaphraseMLMiniLML12V2,
            Self::ParaphraseMlMiniLML12V2Q => fastembed::EmbeddingModel::ParaphraseMLMiniLML12V2Q,
            Self::ParaphraseMlMpnetBaseV2 => fastembed::EmbeddingModel::ParaphraseMLMpnetBaseV2,
            Self::BgeSmallZhv15 => fastembed::EmbeddingModel::BGESmallZHV15,
            Self::BgeLargeZhv15 => fastembed::EmbeddingModel::BGELargeZHV15,
            Self::ModernBertEmbedLarge => fastembed::EmbeddingModel::ModernBertEmbedLarge,
            Self::MultilingualE5Small => fastembed::EmbeddingModel::MultilingualE5Small,
            Self::MultilingualE5Base => fastembed::EmbeddingModel::MultilingualE5Base,
            Self::MultilingualE5Large => fastembed::EmbeddingModel::MultilingualE5Large,
            Self::MxbaiEmbedLargeV1 => fastembed::EmbeddingModel::MxbaiEmbedLargeV1,
            Self::MxbaiEmbedLargeV1Q => fastembed::EmbeddingModel::MxbaiEmbedLargeV1Q,
            Self::GteBaseEnv15 => fastembed::EmbeddingModel::GTEBaseENV15,
            Self::GteBaseEnv15Q => fastembed::EmbeddingModel::GTEBaseENV15Q,
            Self::GteLargeEnv15 => fastembed::EmbeddingModel::GTELargeENV15,
            Self::GteLargeEnv15Q => fastembed::EmbeddingModel::GTELargeENV15Q,
            Self::ClipVitB32 => fastembed::EmbeddingModel::ClipVitB32,
            Self::JinaEmbeddingsV2BaseCode => fastembed::EmbeddingModel::JinaEmbeddingsV2BaseCode,
        }
    }
}
