use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VizierEmbeddingModel {
    AllMiniLml6V2,
    AllMiniLml6V2Q,
    AllMiniLml12V2,
    AllMiniLml12V2Q,
    BgeBaseEnv15,
    BgeBaseEnv15Q,
    BgeLargeEnv15,
    BgeLargeEnv15Q,
    BgeSmallEnv15,
    BgeSmallEnv15Q,
    NomicEmbedTextV1,
    NomicEmbedTextV15,
    NomicEmbedTextV15Q,
    ParaphraseMlMiniLML12V2,
    ParaphraseMlMiniLML12V2Q,
    ParaphraseMlMpnetBaseV2,
    BgeSmallZhv15,
    BgeLargeZhv15,
    ModernBertEmbedLarge,
    MultilingualE5Small,
    MultilingualE5Base,
    MultilingualE5Large,
    MxbaiEmbedLargeV1,
    MxbaiEmbedLargeV1Q,
    GteBaseEnv15,
    GteBaseEnv15Q,
    GteLargeEnv15,
    GteLargeEnv15Q,
    ClipVitB32,
    JinaEmbeddingsV2BaseCode,
}

impl VizierEmbeddingModel {
    pub fn to_fastembed(&self) -> fastembed::EmbeddingModel {
        match self {
            Self::AllMiniLml6V2 => fastembed::EmbeddingModel::AllMiniLML6V2,
            Self::AllMiniLml6V2Q => fastembed::EmbeddingModel::AllMiniLML6V2Q,
            Self::AllMiniLml12V2 => fastembed::EmbeddingModel::AllMiniLML12V2,
            Self::AllMiniLml12V2Q => fastembed::EmbeddingModel::AllMiniLML12V2Q,
            Self::BgeBaseEnv15 => fastembed::EmbeddingModel::BGEBaseENV15,
            Self::BgeBaseEnv15Q => fastembed::EmbeddingModel::BGEBaseENV15Q,
            Self::BgeLargeEnv15 => fastembed::EmbeddingModel::BGELargeENV15,
            Self::BgeLargeEnv15Q => fastembed::EmbeddingModel::BGELargeENV15Q,
            Self::BgeSmallEnv15 => fastembed::EmbeddingModel::BGESmallENV15,
            Self::BgeSmallEnv15Q => fastembed::EmbeddingModel::BGESmallENV15Q,
            Self::NomicEmbedTextV1 => fastembed::EmbeddingModel::NomicEmbedTextV1,
            Self::NomicEmbedTextV15 => fastembed::EmbeddingModel::NomicEmbedTextV15,
            Self::NomicEmbedTextV15Q => fastembed::EmbeddingModel::NomicEmbedTextV15Q,
            Self::ParaphraseMlMiniLML12V2 => fastembed::EmbeddingModel::ParaphraseMLMiniLML12V2,
            Self::ParaphraseMlMiniLML12V2Q => fastembed::EmbeddingModel::ParaphraseMLMiniLML12V2Q,
            Self::ParaphraseMlMpnetBaseV2 => fastembed::EmbeddingModel::ParaphraseMLMpnetBaseV2,
            Self::BgeSmallZhv15 => fastembed::EmbeddingModel::BGESmallZHV15,
            Self::BgeLargeZhv15 => fastembed::EmbeddingModel::BGELargeZHV15,
            Self::ModernBertEmbedLarge => fastembed::EmbeddingModel::ModernBertEmbedLarge,
            Self::MultilingualE5Small => fastembed::EmbeddingModel::MultilingualE5Small,
            Self::MultilingualE5Base => fastembed::EmbeddingModel::MultilingualE5Base,
            Self::MultilingualE5Large => fastembed::EmbeddingModel::MultilingualE5Large,
            Self::MxbaiEmbedLargeV1 => fastembed::EmbeddingModel::MxbaiEmbedLargeV1,
            Self::MxbaiEmbedLargeV1Q => fastembed::EmbeddingModel::MxbaiEmbedLargeV1Q,
            Self::GteBaseEnv15 => fastembed::EmbeddingModel::GTEBaseENV15,
            Self::GteBaseEnv15Q => fastembed::EmbeddingModel::GTEBaseENV15Q,
            Self::GteLargeEnv15 => fastembed::EmbeddingModel::GTELargeENV15,
            Self::GteLargeEnv15Q => fastembed::EmbeddingModel::GTELargeENV15Q,
            Self::ClipVitB32 => fastembed::EmbeddingModel::ClipVitB32,
            Self::JinaEmbeddingsV2BaseCode => fastembed::EmbeddingModel::JinaEmbeddingsV2BaseCode,
        }
    }
}
